version: '3'
services:
  api:
    image: nandus86/predict:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-coquitts
    restart: always
    networks:
      - predict
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.nandus.com.br`) && PathPrefix(`/predict`)"
      - "traefik.http.services.api.loadbalancer.server.port=7010"
    expose:
      - "7010"

networks:
  predict:
    external: true
